package com.algotrader.decision.dataobjects;

import java.time.Instant;

/**
 * Represents a proposed trading action generated by the decision layer.
 *
 * <p>A {@code TradeRecommendation} encapsulates:
 * <ul>
 *     <li>The ticker to trade</li>
 *     <li>The recommended action ({@link Action#BUY} or {@link Action#SELL})</li>
 *     <li>The confidence associated with the recommendation</li>
 *     <li>The quantity to trade</li>
 *     <li>The time at which the action should occur</li>
 * </ul>
 *
 * <p>Trade recommendations are typically derived from higher-level trading
 * decisions such as {@link RoundTripTrade} instances and are consumed by
 * execution components responsible for simulating or executing trades.
 *
 * <p>This class represents a single executable action. More complex trading
 * plans may be composed of multiple recommendations executed over time.
 *
 * <p><b>TODO:</b> Revisit the role of {@code quantity}. Position sizing may
 * ultimately belong elsewhere in the trading pipeline rather than being
 * embedded directly in trade recommendations.
 */
public final class TradeRecommendation { //TODO: this could probably use a rename to something closer to TradeAction

    /**
     * Supported trading actions.
     */
    public enum Action {
        BUY,
        SELL
    }

    private final String ticker;
    private final Action action;
    private final double confidence;
    private final double quantity; //TODO: rethink what the purpose of quantity is, and at what point of the cycle it should be calculated
    private final Instant executionTime;

    /**
     * Creates a trade recommendation.
     *
     * @param ticker ticker symbol to trade
     * @param action trading action to perform
     * @param confidence confidence associated with the recommendation
     * @param quantity quantity to trade
     * @param executionTime the time at which the action should occur
     * @throws IllegalArgumentException if any argument is invalid
     */
    public TradeRecommendation(
            String ticker,
            Action action,
            double confidence,
            double quantity,
            Instant executionTime
    ) {
        validate(ticker, action, confidence, quantity, executionTime);

        this.ticker = ticker;
        this.action = action;
        this.confidence = confidence;
        this.quantity = quantity;
        this.executionTime = executionTime;
    }

    /**
     * Validates constructor arguments before a trade recommendation is created.
     *
     * @throws IllegalArgumentException if any argument is invalid
     */
    private void validate(
            String ticker,
            Action action,
            double confidence,
            double quantity,
            Instant executionTime
    ) {
        if (ticker == null || ticker.isBlank()) {
            throw new IllegalArgumentException("Ticker cannot be null or blank.");
        }

        if (action == null) {
            throw new IllegalArgumentException("Action cannot be null.");
        }

        if (confidence < 0.0 || confidence > 1.0) {
            throw new IllegalArgumentException("Confidence must be between 0 and 1.");
        }

        if (quantity < 0) {
            throw new IllegalArgumentException("Quantity cannot be negative.");
        }

        if (executionTime == null) {
            throw new IllegalArgumentException("Execution time cannot be null.");
        }
    }

    public String getTicker() {
        return ticker;
    }

    public Action getAction() {
        return action;
    }

    public double getConfidence() {
        return confidence;
    }

    public double getQuantity() {
        return quantity;
    }

    public Instant getExecutionTime() {
        return executionTime;
    }

    /**
     * Returns whether this recommendation represents a BUY action.
     *
     * @return {@code true} if the action is {@link Action#BUY}
     */
    public boolean isBuy() {
        return action == Action.BUY;
    }

    /**
     * Returns whether this recommendation represents a SELL action.
     *
     * @return {@code true} if the action is {@link Action#SELL}
     */
    public boolean isSell() {
        return action == Action.SELL;
    }

    @Override
    public String toString() {
        return String.format(
                "TradeRecommendation[ticker=%s, action=%s, confidence=%.2f%%, quantity=%.4f, executionTime=%s]",
                ticker,
                action,
                confidence * 100.0,
                quantity,
                executionTime
        );
    }
}